/*
 * Town -> JAKIM zone, from waktu.solat.my/api/locations.
 *
 * A zone code is not something an operator knows offhand, but the town is, so
 * the picker takes a place name and resolves it to the zone JAKIM files it
 * under. Bundled as a static file rather than fetched: it changes about as
 * often as Malaysian district boundaries do, and the page should not need a
 * second network dependency just to populate a dropdown.
 *
 * Zone membership here is the API operator's, not JAKIM's own table, so the
 * zone list in zones.js stays authoritative for which codes exist.
 */
window.LOCATIONS = [
  ["JHR01", "Pulau Aur"],
  ["JHR01", "Pemanggil"],
  ["JHR02", "Kota Tinggi"],
  ["JHR02", "Mersing"],
  ["JHR02", "Johor Bahru"],
  ["JHR03", "Kluang"],
  ["JHR03", "Pontian"],
  ["JHR04", "Batu Pahat"],
  ["JHR04", "Muar"],
  ["JHR04", "Segamat"],
  ["JHR04", "Gemas"],
  ["KDH01", "Kota Setar"],
  ["KDH01", "Kubang Pasu"],
  ["KDH01", "Pokok Sena"],
  ["KDH02", "Pendang"],
  ["KDH02", "Kuala Muda"],
  ["KDH02", "Yan"],
  ["KDH03", "Padang Terap"],
  ["KDH03", "Sik"],
  ["KDH04", "Baling"],
  ["KDH05", "Kulim"],
  ["KDH05", "Bandar Bahru"],
  ["KDH06", "Langkawi"],
  ["KDH07", "Gunung Jerai"],
  ["KTN01", "Kota Bahru"],
  ["KTN01", "Bachok"],
  ["KTN01", "Pasir Puteh"],
  ["KTN01", "Tumpat"],
  ["KTN01", "Pasir Mas"],
  ["KTN01", "Tanah Merah"],
  ["KTN01", "Machang"],
  ["KTN01", "Kuala Krai"],
  ["KTN01", "Mukim Chiku"],
  ["KTN02", "Jeli"],
  ["KTN02", "Gua Musang"],
  ["KTN02", "Mukim Galas"],
  ["KTN02", "Bertam"],
  ["MLK01", "Bandar Melaka"],
  ["MLK01", "Alor Gajah"],
  ["MLK01", "Jasin"],
  ["MLK01", "Masjid Tanah"],
  ["MLK01", "Merlimau"],
  ["MLK01", "Nyalas"],
  ["NGS01", "Jempol"],
  ["NGS01", "Tampin"],
  ["NGS02", "Kuala Pilah"],
  ["NGS02", "Jelebu"],
  ["NGS02", "Rembau"],
  ["NGS03", "Port Dickson"],
  ["NGS03", "Seremban"],
  ["PHG01", "Pulau Tioman"],
  ["PHG02", "Kuantan"],
  ["PHG02", "Pekan"],
  ["PHG02", "Rompin"],
  ["PHG02", "Muadzam Shah"],
  ["PHG03", "Maran"],
  ["PHG03", "Chenor"],
  ["PHG03", "Temerloh"],
  ["PHG03", "Bera"],
  ["PHG03", "Jerantut"],
  ["PHG03", "Jengka"],
  ["PHG04", "Bentong"],
  ["PHG04", "Raub"],
  ["PHG04", "Kuala Lipis"],
  ["PHG05", "Genting Sempah"],
  ["PHG05", "Janda Baik"],
  ["PHG05", "Bukit Tinggi"],
  ["PHG06", "Bukit Fraser"],
  ["PHG06", "Genting Highlands"],
  ["PHG06", "Cameron Highlands"],
  ["PRK01", "Tapah"],
  ["PRK01", "Slim River"],
  ["PRK01", "Tanjung Malim"],
  ["PRK02", "Ipoh"],
  ["PRK02", "Batu Gajah"],
  ["PRK02", "Kampar"],
  ["PRK02", "Sungai Siput"],
  ["PRK02", "Kuala Kangsar"],
  ["PRK03", "Pengkalan Hulu"],
  ["PRK03", "Grik"],
  ["PRK03", "Lenggong"],
  ["PRK04", "Temengor"],
  ["PRK04", "Belum"],
  ["PRK05", "Teluk Intan"],
  ["PRK05", "Bagan Datuk"],
  ["PRK05", "Kampung Gajah"],
  ["PRK05", "Seri Iskandar"],
  ["PRK05", "Beruas"],
  ["PRK05", "Parit"],
  ["PRK05", "Lumut"],
  ["PRK05", "Sitiawan"],
  ["PRK05", "Pulau Pangkor"],
  ["PRK06", "Selama"],
  ["PRK06", "Taiping"],
  ["PRK06", "Bagan Serai"],
  ["PRK06", "Parit Buntar"],
  ["PRK07", "Bukit Larut"],
  ["PLS01", "Kangar"],
  ["PLS01", "Padang Besar"],
  ["PLS01", "Arau"],
  ["PNG01", "Pulau Pinang"],
  ["SBH01", "Sandakan Timur"],
  ["SBH01", "Bukit Garam"],
  ["SBH01", "Semawang"],
  ["SBH01", "Temanggong"],
  ["SBH01", "Tambisan"],
  ["SBH01", "Sukau"],
  ["SBH02", "Pinangah"],
  ["SBH02", "Terusan"],
  ["SBH02", "Beluran"],
  ["SBH02", "Kuamut"],
  ["SBH02", "Telupid"],
  ["SBH02", "Sandakan Barat"],
  ["SBH03", "Lahad Datu"],
  ["SBH03", "Kunak"],
  ["SBH03", "Silabukan"],
  ["SBH03", "Tungku"],
  ["SBH03", "Sahabat"],
  ["SBH03", "Semporna"],
  ["SBH03", "Tawau Timur"],
  ["SBH04", "Bandar Tawau"],
  ["SBH04", "Balong"],
  ["SBH04", "Merotai"],
  ["SBH04", "Kalabakan"],
  ["SBH04", "Tawau Barat"],
  ["SBH05", "Kudat"],
  ["SBH05", "Kota Marudu"],
  ["SBH05", "Pitas"],
  ["SBH05", "Pulau Banggi"],
  ["SBH06", "Gunung Kinabalu"],
  ["SBH07", "Papar"],
  ["SBH07", "Ranau"],
  ["SBH07", "Kota Belud"],
  ["SBH07", "Tuaran"],
  ["SBH07", "Penampang"],
  ["SBH07", "Kota Kinabalu"],
  ["SBH07", "Putatan"],
  ["SBH07", "Pantai Barat"],
  ["SBH08", "Pensiangan"],
  ["SBH08", "Keningau"],
  ["SBH08", "Tambunan"],
  ["SBH08", "Nabawan"],
  ["SBH09", "Sipitang"],
  ["SBH09", "Membakut"],
  ["SBH09", "Beaufort"],
  ["SBH09", "Kuala Penyu"],
  ["SBH09", "Weston"],
  ["SBH09", "Tenom"],
  ["SBH09", "Long Pa Sia"],
  ["SWK01", "Limbang"],
  ["SWK01", "Sundar"],
  ["SWK01", "Terusan"],
  ["SWK01", "Lawas"],
  ["SWK02", "Niah"],
  ["SWK02", "Sibuti"],
  ["SWK02", "Miri"],
  ["SWK02", "Bekenu"],
  ["SWK02", "Marudi"],
  ["SWK03", "Belaga"],
  ["SWK03", "Sebauh"],
  ["SWK03", "Bintulu"],
  ["SWK03", "Tatau"],
  ["SWK04", "Song"],
  ["SWK04", "Balingian"],
  ["SWK04", "Kapit"],
  ["SWK04", "Igan"],
  ["SWK04", "Kanowit"],
  ["SWK04", "Sibu"],
  ["SWK04", "Dalat"],
  ["SWK04", "Oya"],
  ["SWK05", "Belawai"],
  ["SWK05", "Matu"],
  ["SWK05", "Daro"],
  ["SWK05", "Sarikei"],
  ["SWK05", "Julau"],
  ["SWK05", "Bitangor"],
  ["SWK05", "Rajang"],
  ["SWK06", "Kabong"],
  ["SWK06", "Lingga"],
  ["SWK06", "Sri Aman"],
  ["SWK06", "Engkelili"],
  ["SWK06", "Betong"],
  ["SWK06", "Spaoh"],
  ["SWK06", "Pusa"],
  ["SWK06", "Saratok"],
  ["SWK06", "Roban"],
  ["SWK06", "Debak"],
  ["SWK07", "Samarahan"],
  ["SWK07", "Simunjan"],
  ["SWK07", "Serian"],
  ["SWK07", "Sebuyau"],
  ["SWK07", "Meludam"],
  ["SWK08", "Kuching"],
  ["SWK08", "Bau"],
  ["SWK08", "Lundu"],
  ["SWK08", "Sematan"],
  ["SWK09", "Zon Khas"],
  ["SGR01", "Gombak"],
  ["SGR01", "Hulu Selangor"],
  ["SGR01", "Rawang"],
  ["SGR01", "Hulu Langat"],
  ["SGR01", "Sepang"],
  ["SGR01", "Petaling"],
  ["SGR01", "Shah Alam"],
  ["SGR02", "Sabak Bernam"],
  ["SGR02", "Kuala Selangor"],
  ["SGR03", "Klang"],
  ["SGR03", "Kuala Langat"],
  ["TRG01", "Kuala Terengganu"],
  ["TRG01", "Marang"],
  ["TRG01", "Kuala Nerus"],
  ["TRG02", "Besut"],
  ["TRG02", "Setiu"],
  ["TRG03", "Hulu Terengganu"],
  ["TRG04", "Kemaman"],
  ["TRG04", "Dungun"],
  ["WLY01", "Putrajaya"],
  ["WLY01", "Kuala Lumpur"],
  ["WLY02", "Labuan"]
];

/* "Kuala Lumpur" -> { code, town, state }, for resolving a typed place name. */
window.LOCATION_INDEX = window.LOCATIONS.reduce(function (acc, pair) {
  var code = pair[0];
  var town = pair[1];
  var zone = window.ZONE_INDEX[code];
  // A town whose zone is not in zones.js is skipped rather than offered.
  if (!zone) return acc;
  acc.push({ code: code, town: town, state: zone.state });
  return acc;
}, []);
